server:
  port: 8082
spring:
  application:
    #配置微服务名称
    name: eureka-server
eureka:
  client:
    #当前微服务本身为注册中心，不需要在配置到注册中心是否注册注册中心
    register-with-eureka: false
    #配置注册中心地址
    service-url:
      defaultZone: http://order.qf.com:8080/eureka,http://user.qf.com:8081/eureka
    #配置当前的微服务能否从注册中心获取其他的微服务
    fetch-registry: false
