server:
  port: 10002
spring:
  application:
    #配置微服务名称
    name: consumer-ribbon-server
eureka:
  client:
    #当前微服务是否注册注册中心
    register-with-eureka: true
    #配置注册中心地址
    service-url:
      defaultZone: http://localhost:8080/eureka,http://localhost:8081/eureka,http://localhost:8082/eureka
    #配置当前的微服务能否从注册中心获取其他的微服务
    fetch-registry: true
hystrix:
  command:
    default:
      circuitBreaker:
        #是否开启熔断器
        enabled: true
        #单位时间内，使熔断器跳闸的最小异常请求
        requestVolumeThreshold: 2
        #熔断器跳闸后，在此值的时间的内，hystrix会拒绝新的请求，只有过了这个时间熔断器又会进入半开的状态
        sleepWindowInMilliseconds: 5000
