server:
  port: 10003

spring:
  application:
    name: feign-server
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://order.qf.com:8080/eureka,http://www.qf.com:8082/eureka,http://user.qf.com:8081/eureka
feign:
  hystrix:
    #开启熔断器
    enabled: true
